// Hero figure, "Chile en puntos" (DESIGN.md §5). Geometry and counts come from
// health-map.json, generated by scripts/build-health-map.mjs from the MINSAL snapshot.
import data from "./health-map.json";

export interface HealthMap {
  viewBox: string;
  aspectRatio: string;
  layers: { base: string; highlight: string };
  labels: { name: string; x: number; y: number }[];
  caption: string;
  source: string;
}

const number = new Intl.NumberFormat("es-CL", { maximumFractionDigits: 1 });
const date = new Intl.DateTimeFormat("es-CL", {
  dateStyle: "long",
  timeZone: "UTC",
}).format(new Date(data.source.cutDate));

const { counts, grid } = data;
const excluded = counts.inOperationWithCoordinates - counts.continental;
const degrees = (latitude: number) => `${number.format(Math.abs(latitude))}°`;

export const healthMap: HealthMap = {
  viewBox: data.viewBox,
  aspectRatio: data.aspectRatio,
  layers: { base: data.layers.base, highlight: data.layers.emergency },
  labels: data.labels,
  caption:
    `Chile continental dibujado con sus ${number.format(counts.continental)} establecimientos de salud vigentes con coordenadas, agrupados en una cuadrícula de unos ${grid.cellKm} km: ` +
    `cada uno de los ${number.format(grid.dots)} puntos es una celda con al menos un establecimiento, así que el mapa muestra dónde hay establecimientos, no cuántos. ` +
    `Los ${number.format(grid.emergencyDots)} puntos en guinda, más grandes, son celdas con al menos uno de los ${number.format(counts.emergency)} establecimientos con servicio de urgencia. ` +
    `Del total, el ${number.format(Math.round(counts.band.share))} % está entre los ${degrees(counts.band.north)} y los ${degrees(counts.band.south)} de latitud sur, ` +
    `y la Región Metropolitana reúne ${number.format(counts.metropolitan)}.`,
  source:
    `Fuente: ${data.source.name}, en ${data.source.publisher} (${data.source.license}), corte del ${date}. ` +
    `Quedan fuera ${excluded} establecimientos insulares o con coordenadas fuera del territorio continental.`,
};
